language: ruby
rvm:
  - 2.3.5
services:
  - postgresql
before_script:
  - psql -c "create user danubilla;" -U postgres
  - psql -c "alter user danubilla createdb;" -U postgres
  - psql -c "create database augusta_test;" -U postgres
  - psql -c "alter database augusta_test OWNER TO danubilla;" -U postgres
script:
  - bundle exec rake db:test:prepare
addons:
  postgresql: "9.5"
